/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tp4_segundaversion;

import clases.*;
import java.util.HashSet;

/**
 *
 * @author salon
 */
public class ConsultaM extends javax.swing.JInternalFrame {
        HashSet <Materias>consMateria=MenuPrincipal.materia;
    /**
     * Creates new form ConsultaM
     */
    public ConsultaM() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtAreaM = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jbVer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jtAreaM.setBackground(new java.awt.Color(51, 51, 51));
        jtAreaM.setColumns(20);
        jtAreaM.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N
        jtAreaM.setForeground(new java.awt.Color(0, 204, 0));
        jtAreaM.setRows(5);
        jScrollPane1.setViewportView(jtAreaM);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jbVer.setFont(new java.awt.Font("3270 Nerd Font", 0, 18)); // NOI18N
        jbVer.setText("Ver materias en sistema");
        jbVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(136, Short.MAX_VALUE)
                .addComponent(jbVer)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jbVer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerActionPerformed
        // TODO add your handling code here:
        
        for(Materias m: consMateria){
            jtAreaM.append("Id:"+m.getIdMateria()+" "+"Año. "+m.getAnio()+" "+"Nombre: "+m.getNombreMateria()+"\n"); 
        }
         jtAreaM.append("\n");
    }//GEN-LAST:event_jbVerActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbVer;
    private javax.swing.JTextArea jtAreaM;
    // End of variables declaration//GEN-END:variables
}
