/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tp4_segundaversion;

import clases.*;
import java.awt.Color;

import java.util.HashSet;
import javax.swing.JOptionPane;


/**
 *
 * @author salon
 */
public class InscripcionView extends javax.swing.JInternalFrame {
         HashSet<Materia> materias;
         HashSet<Alumno> alumnos;
         Alumno alumnoSelect =new Alumno();
         Materia materiaSelect=new Materia();
         
    /**
     * Creates new form Inscripcion
     * @param materias
     */
    public InscripcionView(HashSet<Materia> materias, HashSet<Alumno> alumnos) {
        initComponents();
        this.materias=materias;
        this.alumnos=alumnos;
        comboMateria();
        comboAlumno();
        getContentPane().setBackground(Color.DARK_GRAY);
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcComboAl = new javax.swing.JComboBox<>();
        jbInscribir = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbTest = new javax.swing.JButton();
        jcComboMa = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("3270 Nerd Font", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("ELIJA UNA MATERIA:");

        jLabel3.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("ELIJA UN ALUMNO:");

        jcComboAl.setBackground(new java.awt.Color(51, 51, 51));
        jcComboAl.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N
        jcComboAl.setForeground(new java.awt.Color(0, 204, 0));
        jcComboAl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComboAlActionPerformed(evt);
            }
        });

        jbInscribir.setFont(new java.awt.Font("3270 Nerd Font", 1, 24)); // NOI18N
        jbInscribir.setForeground(new java.awt.Color(102, 102, 102));
        jbInscribir.setText("Inscribir");
        jbInscribir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("3270 Nerd Font", 1, 24)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(102, 102, 102));
        jbSalir.setText("Salir");
        jbSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbTest.setText("Test");
        jbTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTestActionPerformed(evt);
            }
        });

        jcComboMa.setBackground(new java.awt.Color(51, 51, 51));
        jcComboMa.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N
        jcComboMa.setForeground(new java.awt.Color(0, 204, 0));
        jcComboMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcComboMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcComboAl, 0, 200, Short.MAX_VALUE)
                    .addComponent(jcComboMa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jbTest)
                        .addGap(121, 121, 121)
                        .addComponent(jbInscribir)
                        .addGap(36, 36, 36)
                        .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jcComboMa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcComboAl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbSalir)
                    .addComponent(jbTest))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTestActionPerformed
        // TODO add your handling code here:
        System.out.println(materias);
        System.out.println(alumnos);
    }//GEN-LAST:event_jbTestActionPerformed

    private void jcComboMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComboMaActionPerformed
        // TODO add your handling code here:
        materiaSelect=(Materia) jcComboMa.getSelectedItem();
    }//GEN-LAST:event_jcComboMaActionPerformed

    private void jcComboAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcComboAlActionPerformed
        // TODO add your handling code here:
        alumnoSelect=(Alumno) jcComboAl.getSelectedItem();
    }//GEN-LAST:event_jcComboAlActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
           alumnoSelect.agregarMateria(materiaSelect);
           JOptionPane.showMessageDialog(this, "Alumno: "+alumnoSelect+" Inscripto en: "+materiaSelect);
       
    }//GEN-LAST:event_jbInscribirActionPerformed
    private void comboAlumno(){
        for(Alumno a : alumnos){
            jcComboAl.addItem(a);
        }
    }
    private void comboMateria(){
        
        for(Materia m : materias){
            jcComboMa.addItem(m);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbTest;
    private javax.swing.JComboBox<Alumno> jcComboAl;
    public javax.swing.JComboBox<Materia> jcComboMa;
    // End of variables declaration//GEN-END:variables
 
}
