/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4_segundaversion;

import java.util.HashSet;
import clases.*;
import java.awt.Color;
import javax.swing.JMenuBar;

/**
 *
 * @author salon
 */
public class MenuPrincipal extends javax.swing.JFrame {
         private HashSet<Materia> materias = new HashSet();
         private HashSet<Alumno> alumnos = new HashSet<>();
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents(); 
        setLocationRelativeTo(null);
        getContentPane().setBackground(Color.BLACK);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JPanel();
        jM = new javax.swing.JMenuBar();
        jmMaterias = new javax.swing.JMenu();
        jmiAltaMaterias = new javax.swing.JMenuItem();
        jmAlumnos = new javax.swing.JMenu();
        jmiAltaAlumnos = new javax.swing.JMenuItem();
        jmInscripcion = new javax.swing.JMenu();
        jmiInscripcion = new javax.swing.JMenuItem();
        jmSalir = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario ");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        escritorio.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 881, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        jM.setForeground(new java.awt.Color(0, 204, 0));
        jM.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N

        jmMaterias.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmMaterias.setForeground(new java.awt.Color(51, 51, 51));
        jmMaterias.setText("Materias");
        jmMaterias.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N
        jmMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmMateriasActionPerformed(evt);
            }
        });

        jmiAltaMaterias.setText("Altas Materias");
        jmiAltaMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAltaMateriasActionPerformed(evt);
            }
        });
        jmMaterias.add(jmiAltaMaterias);

        jM.add(jmMaterias);

        jmAlumnos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmAlumnos.setForeground(new java.awt.Color(51, 51, 51));
        jmAlumnos.setText("Alumnos");
        jmAlumnos.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N

        jmiAltaAlumnos.setText("Altas Alumnos");
        jmiAltaAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAltaAlumnosActionPerformed(evt);
            }
        });
        jmAlumnos.add(jmiAltaAlumnos);

        jM.add(jmAlumnos);

        jmInscripcion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmInscripcion.setForeground(new java.awt.Color(51, 51, 51));
        jmInscripcion.setText("Inscripcion");
        jmInscripcion.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N

        jmiInscripcion.setText("Inscribir");
        jmiInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInscripcionActionPerformed(evt);
            }
        });
        jmInscripcion.add(jmiInscripcion);

        jM.add(jmInscripcion);

        jmSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jmSalir.setForeground(new java.awt.Color(51, 51, 51));
        jmSalir.setText("Salir");
        jmSalir.setFont(new java.awt.Font("3270 Nerd Font", 0, 24)); // NOI18N
        jmSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSalirActionPerformed(evt);
            }
        });

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmSalir.add(jmiSalir);

        jM.add(jmSalir);

        setJMenuBar(jM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmSalirActionPerformed

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInscripcionActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        InscripcionView internalInsc = new InscripcionView(materias,alumnos);
        setLocationRelativeTo(null);
        internalInsc.setVisible(true);
        escritorio.add(internalInsc);
        
    }//GEN-LAST:event_jmiInscripcionActionPerformed

    private void jmiAltaAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaAlumnosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AlumnoView internaAl = new AlumnoView(alumnos);
        setLocationRelativeTo(null);
        internaAl.setVisible(true);
        escritorio.add(internaAl);
    }//GEN-LAST:event_jmiAltaAlumnosActionPerformed

    private void jmMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmMateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmMateriasActionPerformed

    private void jmiAltaMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAltaMateriasActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        MateriaView internalaMat = new MateriaView(materias);
        internalaMat.setVisible(true);
        escritorio.add(internalaMat);
    }//GEN-LAST:event_jmiAltaMateriasActionPerformed
    
        
  
    public HashSet<Materia> getMateria() {
        return materias;
    }

    public  void setMateria(HashSet<Materia> materia) {
        materias = materia;
    }
      public HashSet<Alumno> getAlumno() {
        return alumnos;
    }

    public  void setAlumno(HashSet<Alumno> alumno) {
        alumnos = alumno;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MenuPrincipal().setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel escritorio;
    private javax.swing.JMenuBar jM;
    private javax.swing.JMenu jmAlumnos;
    private javax.swing.JMenu jmInscripcion;
    private javax.swing.JMenu jmMaterias;
    private javax.swing.JMenu jmSalir;
    private javax.swing.JMenuItem jmiAltaAlumnos;
    private javax.swing.JMenuItem jmiAltaMaterias;
    private javax.swing.JMenuItem jmiInscripcion;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables
    
}
